version: '3'

networks:
  vanille:
    driver: bridge

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: dev-env/client.dockerfile
    command: tail -f /dev/null
    ports:
      - '3000:3000' # frontend
      - '4173:4173' # vitepress
      - '5173:5173' # vitepress dev
    volumes:
      - .:/usr/src/client
    networks:
      - vanille

  playwright:
    container_name: playwright
    build:
      context: .
      dockerfile: dev-env/playwright.dockerfile
    command: tail -f /dev/null
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/client
    networks:
      - vanille
