version: '3'

networks:
  vanille:
    driver: bridge

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: docker/client.ci.dockerfile
    image: vanille-client
    command: tail -f /dev/null
    ports:      
      - "3000:3000" # frontend
      - "4173:4173" # vitepress
    networks:
      - vanille

  playwright:
    container_name: playwright
    build:
      context: .
      dockerfile: docker/playwright.ci.dockerfile
    image: vanille-playwright
    ports:
    
      - "3001:3001"
    networks:
      - vanille