name: client-tests

defaults:
 run:
  working-directory: .

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          working-directory: .
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build containers
        run: docker-compose -f docker-compose-ci.yml build playwright
      - name: Install node_modules
        run: docker-compose run playwright yarn
      - name: Run tests
        run: docker-compose run playwright yarn test
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose-ci.yml down
